### ISSUE TITLE
android 11 系统的手机无法进行裁剪

### ISSUE THREAD

**Issue by chztp** [soulqw/CoCo#11]
使用Android11 的手机，图片无法进行裁剪，提示此图片不支持修改功能

**Comment by gznbl** [comment]
选择照片，裁剪完之后卡死
机型：OPPO Ace2 
系统：Android 11

**Comment by soulqw** [comment]
@gznbl 参考demo 你看下Dev 里面的错误日志，有提示你改如何做的

**Comment by soulqw** [comment]
@chztp QQ 群答疑 714178759
