### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by skyCracks** [soulqw/CoCo#13]
执行以下代码：
CoCo.with(this@Fragment)
                    .pick()
                    .then()
                    .dispose()
                    .fileToSaveResult(targetFile)
                    .start(object : CoCoAdapter<DisposeResult>() {
                        override fun onSuccess(data: DisposeResult) {
                          
                        }             
                    })
错误回调报：kotlin.KotlinNullPointerException，是使用lateinit 相关问题，猜测是DisposeBuilder中lateinit var disposer: Disposer

**Comment by soulqw** [comment]
@skyCracks 参考demo里面有一模一样的用法，你看下是不是文件权限没有授予

**Comment by skyCracks** [comment]
文件权限授予了，这个问题只是偶现。

**Comment by soulqw** [comment]
@skyCracks  Ok确认是问题的话可以提PR给我
