### ISSUE TITLE
gradle配置改成这样之后无法调起相机和打开相册

### ISSUE THREAD

**Issue by mzw0517** [soulqw/CoCo#19]
![image](https://user-images.githubusercontent.com/28520774/125226077-f7b1da80-e302-11eb-8cb4-c1ed24ce8175.png)

**Comment by soulqw** [comment]
@mzw0517 目前还未适配targetSDK 30 ，敬请期待后续版本

**Comment by soulqw** [comment]
@mzw0517 已经升级
