### ISSUE TITLE
com.qw.photo.exception.NoFileProvidedException: you need provide a file to finish the operate see:DisposeBuilder.fileToSaveResult

### ISSUE THREAD

**Issue by PiPiCaptain** [soulqw/CoCo#21]
![image](https://user-images.githubusercontent.com/22672329/140906520-a102ab51-9107-438f-a929-434089e26a5a.png)

在相册选择图片时，出现了这样的问题

**Comment by soulqw** [comment]
@PiPiCaptain 错误已经告诉了你解决的方法: dispose之后多调用fileToSaveResult 即可
