### ISSUE TITLE
可以直接显示在imageview上吗

### ISSUE THREAD

**Issue by zfyljx** [soulqw/CoCo#3]
请问可以直接使用imageview.setImageURL(originUri)来显示图片吗

**Comment by soulqw** [comment]
结果里面拿到File了你可直接使用图片加载框架加载或者自行设置即可

**Comment by soulqw** [comment]
@zfyljx 结果里面拿到File了你可直接使用图片加载框架加载或者自行设置即可

**Comment by soulqw** [comment]
@zfyljx  选图片也就是Pick操作符是可以用的,拍照是没有URI的
但是更推荐你直接拿到file再交给图片加载框架去处理,这样拍照和选图片都能使用,通用一点
