### ISSUE TITLE
华为P20上选择图片错误问题

### ISSUE THREAD

**Issue by skyCracks** [soulqw/CoCo#4]
在华为P20 android 版本 10 上选择图片后报：
error on compress or Rotate  java.io.FileNotFoundException: /storage/emulated/0/Pictures/Screenshots/Screenshot_20200529_124657.jpg: open failed: EACCES (Permission denied)
debug跟踪发现是 DefaultImageDisposer中correctRotate()方法处理旋转时出现问题

**Comment by skyCracks** [comment]
继续查了一些资料,发现是因为没有适配Android 10 scoped storage (分区存储)导致的。

**Comment by soulqw** [comment]
@skyCracks 所以只要APP申请了这个权限的话就能正常处理上述逻辑吧?

**Comment by skyCracks** [comment]
> @skyCracks 所以只要APP申请了这个权限的话就能正常处理上述逻辑吧?

权限都申请了,只是在Android Q(10)上面默认需要适配分区存储，选择图片访问了公共目录(/storage/emulated/0/Pictures 属于公共目录)下面的文件,但是没有适配分区存储就会报错，在 application配置加入android:requestLegacyExternalStorage="true 以兼容模式运营就不会报错。
